services:
  python_docker:
    build:
      context: ./files
      dockerfile: Dockerfile
    ports:
      - ${PORT}:16000
    networks:
      knowledge_graph:
        aliases:
          - python_docker

networks:
  knowledge_graph:
    name: knowledge_graph
    driver: bridge